### PR TITLE
fix offset in model fitting

### LINKED ISSUE #29: mgcv::bam uses the offset as a covariate
😱😱😱😱

Only when specified in the formula, by the looks of it. This makes extrapolation behave in some very weird ways, e.g. places with more kids have far fewer school contacts.

Will investigate and can always pass in with the offset argument instead

### PR DESCRIPTION
**Pull request by goldingn**
fixes #29

### CODE REVIEW

File: R/fit_single_contact_model.R [hunk 1]
```diff
@@ -26,7 +26,7 @@ fit_single_contact_model <- function(contact_data, population) {
       contacts ~
       # multiplicative offset for population in the 'to' age group, to account for
       # opportunity to contact
-      stats::offset(log(pop_age_to)) +
```
Comment (goldingn) [inline R/fit_single_contact_model.R:29]: @njtierney this was the bug - I think because `offset()` is a special, so parsed in interpreting the formula, rather than the function being executed. Although there is a function in stats with this name (which does nothing), nammespacing it here trips up the formula interpretation, and causes it to be used as covariate.
